apiVersion: 1

datasources:
  - name: "GCP Monitoring"
    type: stackdriver
    access: proxy
    isDefault: true
    jsonData:
      tokenUri: "https://oauth2.googleapis.com/token"
      authenticationType: "gce"
      
      defaultProject: "${GCP_PROJECT_ID}"