name: Terraform Deploy
on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    env:
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_db_user: ${{ secrets.DB_USER }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_image_url: ${{ secrets.IMAGE_URL }}
      TF_VAR_db_instance_name: ${{ secrets.DB_INSTANCE_NAME }}
      TF_VAR_redis_instance_name: ${{ secrets.REDIS_INSTANCE_NAME }}
      TF_VAR_gcp_region: ${{ secrets.GCP_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Import existing resources (Cloud SQL + Redis)
        run: |
          # Importa a instância do Cloud SQL
          terraform import google_sql_database_instance.default \
            projects/${{ secrets.GCP_PROJECT_ID }}/instances/${{ secrets.DB_INSTANCE_NAME }} || true

          # Importa apenas o database dentro da instância
          terraform import google_sql_database.default \
            projects/${{ secrets.GCP_PROJECT_ID }}/instances/${{ secrets.DB_INSTANCE_NAME }}/databases/${{ secrets.DB_NAME }} || true

          # Importa a instância do Redis
          terraform import google_redis_instance.default \
            projects/${{ secrets.GCP_PROJECT_ID }}/locations/${{ secrets.GCP_REGION }}/instances/${{ secrets.REDIS_INSTANCE_NAME }} || true
        continue-on-error: true

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && steps.plan.outcome == 'success'
        run: terraform apply -input=false -auto-approve

      - name: Set Env Variables from Terraform Outputs
        if: steps.apply.outcome == 'success'
        run: |
          echo "DB_PRIVATE_IP=$(terraform output -raw db_private_ip_address)" >> $GITHUB_ENV
          echo "REDIS_HOST=$(terraform output -raw redis_host)" >> $GITHUB_ENV


      - name: Download Cloud SQL Auth Proxy
        if: steps.apply.outcome == 'success'
        run: |
          wget -O cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.1/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy

      - name: Run SQL init script via Cloud SQL Proxy
        if: steps.apply.outcome == 'success'
        run: |
          export DB_USER="${{ secrets.DB_USER }}"
          export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          export DB_NAME="${{ secrets.DB_NAME }}"
          export DB_INSTANCE="${{ secrets.GCP_PROJECT_ID }}:${{ secrets.GCP_REGION }}:${{ secrets.DB_INSTANCE_NAME }}"
          ./cloud-sql-proxy --address 127.0.0.1 --port 5432 --credentials-file='${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' $DB_INSTANCE &
          sleep 5
          docker run --rm \
            -e PGPASSWORD=$DB_PASSWORD \
            -v $(pwd):/workspace \
            postgres:15 \
            psql -h 127.0.0.1 -U $DB_USER -d $DB_NAME -f /workspace/terraform/init.sql
          kill %1

      - name: Terraform Output
        id: output
        if: steps.apply.outcome == 'success'
        run: |
          echo "Cloud Run URL: $(terraform output -raw cloudrun_url)"